### ISSUE TITLE
Provide guidance for algorithm selection?

### ISSUE THREAD

**Issue by deklanw** [GiulioRossetti/cdlib#100]
It seems like a small table or flowchart could be useful for this library. Something like:

"< 5000 nodes, sparse. Try these: ... "
"< 5000 nodes, dense. Try these: ... "
">= 5000 nodes, sparse. Try these: ... "
">= 5000 nodes, dense. Try these: ... "

I'm not sure what the exact criteria would be, but this is just a rough idea. In particular, some of these algorithms aren't very feasible for large graphs. At least some big O runtime notes would be helpful.

Also, it seems like in most cases someone would either be using algorithms with a preset number of communities, or not. It seems like separating these algorithms might be useful.

Afaik some of these algorithms are considered to be strict improvements on others,
CONGO > CONGA
Angel > Demon
In these cases would it be helpful to put the supplanted algorithms somewhere separate?

**Comment by Yquetzal** [comment]
Thanks for the recommendation, that's a good idea. I'm not sure about the "strict improvements", because often, what is superior to what is somewhat arbitrary... Bu the evaluation of performance could be done relatively easily and somewhat automatically. In your opinion, if we create something like that, i.e., a summary of information on methods such as scalability, if they need a number of communities or not, if they accept weighted/directed graphs... Where should this appear ? In the documentation ?

**Comment by deklanw** [comment]
I think anywhere is okay. I would personally like it on this page https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/node_clustering.html as additional columns, and in the notes on the individual algorithm page. I'm not sure why this table is so narrow, but it looks like it could take up more space.

For requiring # of communities vs not I think that distinction is almost so important as to justify splitting into two tables.

**Comment by BrandonKMLee** [comment]
The same can be said for whether a graph can accept directed graphs or not.

- label_propagation, louvain, markov_clustering, spinglass, aslpaw, chinesewhispers, edmot, der and cpm failed to use Directed Graphs.
- eigenvector, leiden, rb_pots and rber_pots can use DIrected Graphs.
