### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by RinyBua** [GiulioRossetti/cdlib#134]
I would like to try this package but I couldn't install it.

I tried to install CDlib lastest version
Operating System: macOS Catalina 10.15.7
Python version: 3.8.6

when I installed it, I got this error:
_ERROR: Could not find a version that satisfies the requirement completely-shuffle>=0.9.2 (from shuffle-graph>=1.1.2->ASLPAw->cdlib==0.1.9) (from versions: none)
ERROR: No matching distribution found for completely-shuffle>=0.9.2 (from shuffle-graph>=1.1.2->ASLPAw->cdlib==0.1.9)_

I have tried to install the required packages manually but didn't work either. Is this because of my computer? Do you have any advice?

Thank you
Best regards.

**Comment by GiulioRossetti** [comment]
Hi,
the issue is a pretty new one: on the 30th of October a new version of shuffle-graph was released but - for now I assume - without support for python 3.8.x

My suggestion is to force the installation of a previous version of shuffle-graph before installing CDlib. This will solve your issue.

Best,
Giulio
