### ISSUE TITLE
Wrong Incorrect NMI exception

### ISSUE THREAD

**Issue by agb94** [GiulioRossetti/cdlib#196]
**Describe the bug**

`cdlib.evaluation.overlapping_normalized_mutual_information_LFK` produces the `incorrect NMI` exception when two clusterings are exactly the same because the output NMI is `1.0000000000000002`, which is greater than `1.0`.

**To Reproduce**
- CDlib version: 0.2.4
- Operating System: Ubuntu 16.04
- Python version: 3.8.2
- Version(s) of CDlib required libraries

```
>>> nc1 = cdlib.NodeClustering([[0,3], [7,8], [5,6], [10], [9], [4], [2], [1]], graph=None)
>>> nc2 = cdlib.NodeClustering([[0,3], [5,6], [8,7], [1], [2], [4], [9], [10]], graph=None)
>>> cdlib.evaluation.overlapping_normalized_mutual_information_LFK(nc1, nc2)
NMI: 1.0000000000000002  from -1.2172814056727293e-16 -1.2172814056727293e-16 4.249600241524693 4.249600241524693 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabin/.pyenv/versions/3.8.2/lib/python3.8/site-packages/cdlib/evaluation/comparison.py", line 131, in overlapping_normalized_mutual_information_LFK
    score=onmi.onmi(
  File "/home/gabin/.pyenv/versions/3.8.2/lib/python3.8/site-packages/cdlib/evaluation/internal/onmi.py", line 141, in onmi
    raise Exception("incorrect NMI")
Exception: incorrect NMI
```

**Expected behavior**

No exception
 
**Screenshots**

**Additional context**

**Comment by GiulioRossetti** [comment]
You are running into the old problem with floating point numbers that not all numbers can be represented exactly. 

With floating point representation, your rounded version and 1.0 are the same number. Since computers are binary, they store floating point numbers as an integer and then divide it by a power of two.

Double precision numbers have 53 bits (16 digits) of precision and regular floats have 24 bits (8 digits) of precision. The floating point type in Python uses double precision to store the values.

**Comment by agb94** [comment]
@GiulioRossetti

Thanks for your answer.
However, the problem is that even though the rounded version of `1.0000000000000002` is equal to `1.0`, **`cdlib` produces the `incorrect NMI` exception** because of the if statement `if NMI < 0 or NMI > 1 or math.isnan(NMI):` in 'onmi.py:139`.

**Comment by GiulioRossetti** [comment]
That's completely another issue, thanks for raising it. I'll provide the bugfix within the day in the repository.
