### ISSUE TITLE
Fixing Number of Communities for Leiden Algorithm

### ISSUE THREAD

**Issue by rudra0713** [GiulioRossetti/cdlib#216]
Hi,
   I am a fairly new user of community detection algorithms. I started experimenting with the Leiden algorithm and I am not finding an easy way to specify the number of communities I want. I checked 
https://github.com/vtraag/leidenalg/issues/89
and tried to specify the `initial_membership` option. However, I could not figure out a way to use the optimizer with the cdlib library.

Any help will be greatly appreciated.

**Comment by Yquetzal** [comment]
Hi,
unless I'm missing something, leiden is not designed to specify a number of desired communities. Unlike other approaches, leiden, like Louvain --the method it improves-- is designed to automatically discover the right number of communities. When one wants to tune this number, one usually tune the resolution parameter. However our current implementation do not accept this resolution parameter, unlike the original implementation. That is a possible improvement for the future **accepting additional parameters for leiden, in particular the resolution parameter**

**Comment by rudra0713** [comment]
Thanks a lot, @Yquetzal for your response. Can you kindly suggest me some community detection algorithms (implemented in cdlib) that take the number of communities as input?

**Comment by Yquetzal** [comment]
Not really, we do not have a distinct category for such methods. Your best chance is to look at the list of methods:
https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/node_clustering.html
Among classic algorithms, the girvan newman one has a level parameter allowing to choose the number of communities https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/algs/cdlib.algorithms.girvan_newman.html#cdlib.algorithms.girvan_newman
Otherwise I see for instance that the first method in the list, `agdl` has  a `number_communities` parameter...

**Comment by rudra0713** [comment]
Thanks a lot, @Yquetzal. I will look into the details.
