### ISSUE TITLE
Bugs on CDLib for bipartite community detection

### ISSUE THREAD

**Issue by Natkamon** [GiulioRossetti/cdlib#226]
**Describe the bug**
I am using CDLib for bipartite community detection and found the following bugs.
1. [cdlib.algorithms.bimlpa] The example provided in the documentation doesn't work. It throws an error: "It returns ZeroDivisionError: float division by zero".
2. [cdlib.algorithms.condor] The example uses `G = nx.karate_club_graph()` that is not bipartite graph. So when I run an example, it throws an error: "AssertionError: The network must be bipartite." However, I run this method on my bipartite graph and it works. Moreover, the description explained that `Works on weighted and unweighted graphs.` but in the table `Weighted == No`.
3. [cdlib.algorithms.CPM_Bipartite] The method seems to work incorrectly. I run an example code, and it returns communities contain only one node, i.e., `coms.communities = [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9],  [10], ...`.
4. [cdlib.algorithms.infomap_bipartite]. The example code doesn't work on my machine even though I installed "wurlitzer" package.

`ModuleNotFoundError: No module named 'fcntl'`
`ModuleNotFoundError: Optional dependency not satisfied: install package wurlitzer to use infomap.`

I cannot install "fcntl" module, probably because I use Windows. (https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl)

6. [cdlib.algorithms.spectral] 1) The graph used in the example is not bipartite (i.e., `G = nx.karate_club_graph()`). 2) coms = algorithms.spectral(G) required kmax parameter so it throws an error: `NetworkXError: row_order is empty list`.

**To Reproduce**
- CDlib version : 0.3.0
- Operating System : Windows 11
- Python version : 3.9.7
- Version(s) of CDlib required libraries : networkx==3.1, informap==2.7.1, wurlitzer==3.0.3, igraph==0.10.6, leidenalg=0.10.1

**Comment by GiulioRossetti** [comment]
Thanks for opening the issue: I'll work on it as soon as possible.

**Comment by GiulioRossetti** [comment]
I gave a look at the issues you reported.

1. The network used as an example in the documentation has been changed: the error was due to the specific topology (given the parameter used, the generated network wasn't connected);
2. Documentation updated;
3. It is probably a result tied to your graph topology. I tested several randomly generated bipartite graphs and for none of them, I obtained exclusively clusters composed of singletons;
4. Have you checked the version of informap (>=1.3.0) and wurlitzer (>=1.0.2) installed in your environment? Indeed fcntl is not supported on Windows but checking both my Osx and GNU/Linux envs I don't see it installed... maybe it is just a dependency of older versions of such packages. Unfortunately, I don't have a Windows 11 machine to replicate the tests;
5. The Spectral clustering algorithm implemented is not designed for bipartite graphs - see the original paper in the docs. Indeed that was an error in the description table for the method. I fixed the example adding the (mandatory) missing parameter.

Best,
Giulio

**Comment by Natkamon** [comment]
I saw the documentation fixed on GitHub but not yet on the library website: https://cdlib.readthedocs.io/en/latest/.

1. **[cdlib.algorithms.bimlpa]** I am able to run the example code but need to check that `nx.is_connected(G) == True`. Do you think it would be good to add one sentence that: "This method works for the connected graph."?
2. **[cdlib.algorithms.condor]** Perfect!
3. **[cdlib.algorithms.CPM_Bipartite]** I run the code with the same example in the documentation. However, the result still returns exclusive clusters. Note that my `leidenalg` version is 0.10.1.

![image](https://github.com/GiulioRossetti/cdlib/assets/2323724/e09760f7-6b4c-48f2-8e97-e235814ad0be)

4. **[cdlib.algorithms.infomap_bipartite]** Yes, my infomap and wurlitzer versions are 2.7.1 and 3.0.3, respectively. So, The method doesn't work on my Windows probably because I cannot install `fcntl`. Nonetheless, in the documentation, the example is still using `G = nx.karate_club_graph()`.
5. OK.

Thank you for your immediate response to my issue!

**Comment by GiulioRossetti** [comment]
Hi, one of the commits was not pushed to the main, sorry!

Here are the updates:

1. Statement added in the docs;
2. Good!
3. I made some additional tests: try lowering the resolution limit - probably, setting it to 1 is a somewhat excessive constraint for the specific topology. Please take a look at the example in the docs.
4. Docs updated. Indeed, this hidden dependency on fcntl for Windows systems is not particularly nice... I'll see what can be done in a future release - at the moment, I don't have a fi for that, I'm afraid.
5. Good!

**Comment by Natkamon** [comment]
3. It works now on my machine with the new example in the docs, i.e., `resolution_parameter_01 = 0.5`.

I also saw the updated docs on the library website.

Thanks a lot for resolving the issue. Grazie mille!

**Comment by Natkamon** [comment]
It works now on my machine with the new example in the docs, i.e., resolution_parameter_01 = 0.5.
I also saw the updated docs on the library website.

Thanks a lot for resolving the issue. Grazie mille!
